# Generated by Django 5.0 on 2023-12-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customerName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('emergencyNumber', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('package', models.CharField(choices=[('Student', 'Student'), ('General', 'General'), ('Resident', 'Resident')], max_length=30)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
