# Generated by Django 5.0 on 2024-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_customer_last_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_paid",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
