# Generated by Django 5.0 on 2024-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_customer_last_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="created_at",
            new_name="admission_date",
        ),
        migrations.AddField(
            model_name="customer",
            name="assigned_trainer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="cnic",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="monthly_fee",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="nationality",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="relationship",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="special_training_fee",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="voucher_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="package",
            field=models.CharField(
                choices=[
                    ("Staff Member", "Staff Member"),
                    ("Deans Employee", "Deans Employee"),
                    ("Resident", "Resident"),
                    ("General", "General"),
                    ("Student", "Student"),
                    ("Other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
