# Generated by Django 5.0 on 2024-02-28 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_rename_created_at_customer_admission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="due_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
