# Generated by Django 5.0 on 2024-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_customer_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
