# Generated by Django 5.0 on 2024-03-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_customer_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="package",
            field=models.CharField(max_length=30),
        ),
    ]
