# Generated by Django 5.0 on 2024-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_alter_customer_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="package",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customer",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
