# Generated by Django 5.0 on 2024-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_alter_customer_assigned_trainer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="assigned_trainer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="special_training_fee",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
