# Generated by Django 5.0 on 2024-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_alter_customer_assigned_trainer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="admission_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
