# Generated by Django 5.0 on 2024-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_customer_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cnic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
