# Generated by Django 5.0 on 2024-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_alter_customer_address_alter_customer_cnic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="emergency_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
